// Generated by CoffeeScript 1.7.1
(function() {
  var StaticHandlebarsCompiler, debug, fs, glob, handlebars, mkdirp, progeny, sysPath;

  handlebars = require("handlebars");

  sysPath = require("path");

  fs = require("fs");

  glob = require("glob");

  mkdirp = require("mkdirp");

  debug = require("debug")("brunch:staticHandlebars");

  progeny = require("progeny");

  module.exports = StaticHandlebarsCompiler = (function() {
    StaticHandlebarsCompiler.prototype.brunchPlugin = true;

    StaticHandlebarsCompiler.prototype.type = "template";

    StaticHandlebarsCompiler.prototype.extension = "hbs";

    function StaticHandlebarsCompiler(config) {
      var _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
      this.config = config;
      this.outputDirectory = ((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? (_ref2 = _ref1.staticHandlebars) != null ? _ref2.outputDirectory : void 0 : void 0 : void 0) || 'public';
      this.templatesDirectory = ((_ref3 = this.config) != null ? (_ref4 = _ref3.plugins) != null ? (_ref5 = _ref4.staticHandlebars) != null ? _ref5.templatesDirectory : void 0 : void 0 : void 0) || 'app/templates';
      this.partialsDirectory = ((_ref6 = this.config) != null ? (_ref7 = _ref6.plugins) != null ? (_ref8 = _ref7.staticHandlebars) != null ? (_ref9 = _ref8.partials) != null ? _ref9.directory : void 0 : void 0 : void 0 : void 0) || this.templatesDirectory;
      this.partialsPrefix = ((_ref10 = this.config) != null ? (_ref11 = _ref10.plugins) != null ? (_ref12 = _ref11.staticHandlebars) != null ? (_ref13 = _ref12.partials) != null ? _ref13.prefix : void 0 : void 0 : void 0 : void 0) || '';
      this.staticData = ((_ref14 = this.config) != null ? (_ref15 = _ref14.plugins) != null ? (_ref16 = _ref15.staticHandlebars) != null ? _ref16.data : void 0 : void 0 : void 0) || {};
      this.rootPath = ((_ref17 = this.config) != null ? (_ref18 = _ref17.paths) != null ? _ref18.root : void 0 : void 0) || process.cwd();
      this.getDependencies = progeny({
        rootPath: this.rootPath,
        extension: 'hbs',
        extensionsList: ['hbs'],
        regexp: /^\s*\{\{> ([\w]*)\}\}/,
        exclusion: /a^/,
        prefix: this.partialsPrefix
      });
    }

    StaticHandlebarsCompiler.prototype.withPartials = function(callback) {
      var errThrown, partials;
      partials = {};
      errThrown = false;
      return glob(sysPath.join(this.partialsDirectory, this.partialsPrefix + '*.hbs'), (function(_this) {
        return function(err, files) {
          if (err != null) {
            return callback(err);
          } else if (!files.length) {
            return callback(null, partials);
          } else {
            return files.forEach(function(file) {
              var name;
              name = sysPath.basename(file, ".hbs");
              if (this.partialsPrefix != null) {
                name = name.substr(this.partialsPrefix.length);
              }
              return fs.readFile(file, function(err, data) {
                if ((err != null) && !errThrown) {
                  errThrown = true;
                  return callback(err);
                } else {
                  partials[name] = data.toString();
                  if (Object.keys(partials).length === files.length) {
                    return callback(null, partials);
                  }
                }
              });
            });
          }
        };
      })(this));
    };

    StaticHandlebarsCompiler.prototype.compile = function(data, path, callback) {
      var basename, err, template;
      try {
        basename = sysPath.basename(path, ".hbs");
        template = handlebars.compile(data);
        return this.withPartials((function(_this) {
          return function(err, partials) {
            var html, newPath, relPath;
            if (err != null) {
              return callback(err);
            } else {
              html = template(_this.staticData, {
                partials: partials,
                helpers: _this.makeHelpers(partials)
              });
              relPath = sysPath.relative(_this.templatesDirectory, path);
              newPath = sysPath.join(_this.outputDirectory, relPath.slice(0, -4) + ".html");
              mkdirp.sync(sysPath.dirname(newPath));
              debug('writing file', newPath);
              return fs.writeFile(newPath, html, function(err) {
                return callback(err, null);
              });
            }
          };
        })(this));
      } catch (_error) {
        err = _error;
        return callback(err, null);
      }
    };

    StaticHandlebarsCompiler.prototype.makeHelpers = function(partials) {
      return {
        partial: function(partial, options) {
          return new handlebars.SafeString(handlebars.compile(partials[partial])(options.hash));
        }
      };
    };

    return StaticHandlebarsCompiler;

  })();

}).call(this);
